version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456